=== thomasRambaldi/M1ProjetXML/projet.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT master (parcours+, intervenant+)>
<!ELEMENT unite    (nom, ref-intervenant*, nbCredits, resume, plan?, lieu?)>
<!ELEMENT nom      (#PCDATA)>
<!ELEMENT idUE  (#PCDATA)>
<!ELEMENT nbCredits     (#PCDATA)>
<!ELEMENT resume     (#PCDATA)>
<!ELEMENT plan     (#PCDATA)>
<!ELEMENT lieu     (#PCDATA)>
<!ELEMENT mail     (#PCDATA)>
<!ELEMENT web     (#PCDATA)>

<!ELEMENT intervenant (nom, mail, web)>
<!ELEMENT ref-intervenant (#PCDATA)>
<!ELEMENT ref-unite (#PCDATA)>

<!--
<!ENTITY  lum  "Luminy">
<!ENTITY  stCh  "Saint-Charles">
<!ENTITY  stJe  "Saint-Jérome">
-->

<!ATTLIST  unite  id  ID  #IMPLIED>
<!ATTLIST  ref-intervenant  ref  IDREF  #REQUIRED>
<!ATTLIST  ref-unite  ref  IDREF  #REQUIRED>
<!ATTLIST  intervenant  id  ID  #REQUIRED>
<!ATTLIST  parcours  id  ID  #REQUIRED>


<!ELEMENT parcours (nom, ref-intervenant*, description, semestre+, debouche+)>
<!ELEMENT responsable (intervenant+)>
<!ELEMENT nomRes  (#PCDATA)>
<!ELEMENT description     (#PCDATA)>
<!ELEMENT debouche   (#PCDATA)>

<!ELEMENT semestre (unite+)>
<!ATTLIST unite role (obligatoire|option) #IMPLIED>
<!ATTLIST semestre numero (1|2|3|4) #IMPLIED>


<!--
<!ENTITY  dom.luminy  "univ-mrs.fr" >
<!ENTITY  dom.dil     "dil.&dom.luminy;" >
-->


<!--
Définissez, quand cela est possible, des entités paramètre pour 
le contenu des éléments complexes.
-->





<!--
<!ATTLIST  produit  id  ID  #IMPLIED>

<!ATTLIST prix
    monnaie (Euros|Francs) #IMPLIED >

<!ATTLIST nature
    natureProduit (Final|Intermediaire) #IMPLIED >

<!ENTITY  nom_entité  "valeur">
<!ENTITY  dom.luminy  "univ-mrs.fr" >
<!ENTITY  dom.dil     "dil.&dom.luminy;" >
<!ENTITY ex2 SYSTEM "exemple2.xml">

<!ELEMENT  voisin  (#PCDATA)>
<!ATTLIST  voisin  ref  IDREF  #REQUIRED>
-->


<!--
Ajoutez à votre DTD une entité paramètre interne qui définie le contenu
d'un produit et utilisez cette entité dans la définition de l'élément
produit.
-->

=== thomasRambaldi/M1ProjetXML/projet.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--
<!DOCTYPE master SYSTEM "projet.dtd"[
	<!ENTITY  dom.luminy  "univ-mrs.fr" >
	<!ENTITY  dom.dil     "dil.&dom.luminy;" >
	
	<!ENTITY  lum  "Luminy">
	<!ENTITY  stCh  "Saint-Charles">
	<!ENTITY  stJe  "Saint-Jérome">
]>
-->

<!DOCTYPE master [
	<!ENTITY  dom.luminy  "univ-mrs.fr" >
	<!ENTITY  dom.dil     "dil.&dom.luminy;" >
	
	<!ENTITY  lum  "Luminy">
	<!ENTITY  stCh  "Saint-Charles">
	<!ENTITY  stJe  "Saint-Jérome">
]>

<master	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="projet.xsd">
			
	<parcours id="TC">
		<nom>Tronc commun</nom>
		
			<ref-intervenant ref="morin"/>
			<ref-intervenant ref="massat"/>
		
		<description>Description du master</description>
	
		<semestre numero="1">
			<unite role="obligatoire" id="ENSINAU1">
				<nom>Génie Logiciel</nom>
				
					<ref-intervenant ref="arrighi"/>
					<ref-intervenant ref="perrot"/>
				
				<nbCredits>6</nbCredits>
				
				<resume>
					Processus logiciel
					Gestion de projet
					Spécification et conception (artefact : notation UML)
					Design patterns
				</resume>
				<plan>Cours/TD/TP : 20h/20h/20h</plan>
				<lieu>Luminy</lieu>
				
			</unite>
			
			<unite role="obligatoire" id="ENSINAU2">
				<nom>Complexité</nom>
				
					<ref-intervenant ref="perrot"/>
					<ref-intervenant ref="creignou"/>
				
				<nbCredits>6</nbCredits>
				<resume>
					Rappels sur les notions d'analyse de la complexité des algorithmes et des problèmes.
					Notion de problèmes (décision, recherche, dénombrement, énumération, optimisation). Bornes inférieures de complexité.
					Classes P et NP. Problèmes NP-complets.
					Méthodes de résolution des problèmes NP-Complets.
				</resume>
				<plan>Cours/TD/TP : 20h/20h/20h</plan>
				<lieu>Luminy</lieu>
			</unite>
			 
			<unite role="obligatoire" id="ENSINAU3">
				<nom>Réseaux</nom>
				
				<ref-intervenant ref="godard"/>
				
				<nbCredits>6</nbCredits>
				<resume>
					Architecture en couches, standard OSI
					Couche physique
					Couche liaison de Données
					Réseau IP
					Algorithmes de routage, routage IP
					Protocole TCP/IP
					Couche Application : HTTP, SMTP, FTP, ...
					Bases des protocoles cryptographiques (terminologie, architecture à clef publique).
					Introduction à la Sécurité des réseaux.
				</resume>
				<plan>Cours/TD/TP : 20h/20h/20h</plan>
				<lieu>Luminy</lieu>
			</unite> 
			
			<unite role="obligatoire" id="ENSINAU4">
				<nom>Programmation fonctionnelle</nom>
				
				<ref-intervenant ref="santocanale"/>
				
				<nbCredits>3</nbCredits>
				<resume>
					1- Introduction à la programmation fonctionnelle, sur l'exemple du langage
					OCaml
					Expressions, évaluation, types de base. Polymorphisme, ordre supérieur.
					Fonctions récursives, filtrage. Les diverses stratégies d'évaluation, application à la programmation d'un opérateur de point fixe.
					2- Les types
					Sommes, types récursifs, polymorphes. Arbres. Filtrage.
					3- Sémantique opérationnelle
					Liaisons, environnements, clôtures. Évaluation des fonctions récursives .
					4- Aspects impératifs
					Exceptions, entrées-sorties, séquencement, fichiers, références, tableaux, enregistrements.
					5- Implantation du filtrage en OCaml
					Termes formels, substitutions, filtrage.
				</resume>
				<plan>Cours/TD/TP : 10h/10h/10h</plan>
				<lieu>Luminy</lieu>
			</unite>
			 
			<unite role="obligatoire" id="ENSINAU12">
				<nom>BDR : approfondissement</nom>
				
					<ref-intervenant ref="sabatier"/>
					<ref-intervenant ref="novelli"/>
				
				<nbCredits>3</nbCredits>
				<resume>
					nous sommes désolé, mais nous n'avons pas encore de resume.
				</resume>
				<plan>Cours/TD/TP : 10h/10h/10h</plan>
				<lieu>Luminy</lieu>
			</unite>
			 
			<unite role="option" id="ENSINAU6">
				<nom>Programmation logique</nom>
				<nbCredits>3</nbCredits>
				<resume>
					Introduction. Forme générale des règles. Effacement, unification, backtracking. Contrôle de l'exécution.
					Listes, arbres et n-uplets. Liste représentée par différence de listes. Ajout en tête et en queue, concaténation.
					Analyseurs syntaxiques. Construction d'un arbre syntaxique. Liste des feuilles d'un arbre. Freeze et analyse par feuille.
					Règles prédéfinies.
				</resume>
				<plan>Cours/TD/TP : 10h/10h/10h</plan>
				<lieu>Luminy</lieu>
			</unite>
			 
			<unite role="option" id="ENSINAU7">
				<nom>Outils de l'internet</nom>
				<nbCredits>3</nbCredits>
				<resume>
					Présentation d'Internet.
					Les langages et les normes sur Internet.
					Les protocoles : HTTP, HTTP, SMTP, IMAP, POP3
					Les applications web.
					Sécurité.
					Les nouvelles et futures technologies.
				</resume>
				<plan>Cours/TD/TP : 10h/10h/10h</plan>
				<lieu>Luminy</lieu>
			</unite> 
			
			<unite role="option" id="ENSINAU8">
				<nom>Système embarqué</nom>
				<ref-intervenant ref="niebert"/>
				<nbCredits>3</nbCredits>
				<resume>
					nous sommes désolé, mais nous n'avons pas encore de resume.
				</resume>
				<plan>Cours/TD/TP : 10h/10h/10h</plan>
				<lieu>Luminy</lieu>
			</unite>
			 
			<unite role="option" id="ENSINAU9">
				<nom> Fondamentaux pour l'ingénierie des langues</nom>
				
					<ref-intervenant ref="bechet"/>
					<ref-intervenant ref="ramisch"/>
					
				<nbCredits>3</nbCredits>
				<resume>
					Rappel de théorie des langages
					Algorithmes d'analyse syntaxique pour grammaires ambiguës
					Transducteurs finis et leur application en TAL
				</resume>
				<plan>Cours/TD/TP : 10h/10h</plan>
				<lieu>Luminy</lieu>
			</unite> 
			
			<unite role="option" id="ENSINAU10">
				<nom>Modèles à évènements discrets</nom>
				<nbCredits>3</nbCredits>
				<resume>
					Posséder les notions de base en modélisation et analyse de systèmes dynamiques à événements discrets et particulièrement appréhender le formalisme réseau de
					Pétri. Étudier la conception et la spécification des systèmes réactifs à travers l'analyse du modèle à évènements discrets (concurrence, parallélisme, synchronisation).
				</resume>
				<plan>Cours/TD : 20h/10h</plan>
				<lieu>Luminy</lieu>
			</unite> 
			
			<unite role="option" id="ENSINAU13">
				<nom>Pratique de la cryptographie</nom>
				<ref-intervenant ref="morin"/>
				<nbCredits>3</nbCredits>
				<resume>
					nous sommes désolé, mais nous n'avons pas encore de resume.
				</resume>
				<plan>Cours/TD/TP : 20h/20h/20h</plan>
				<lieu>Luminy</lieu>
			</unite>  
		</semestre>
				
		<semestre numero="2">
			<unite role="obligatoire" id="ENSINBU1">
				<nom>Anglais</nom>
				<nbCredits>3</nbCredits>
				<resume>
					Un enseignement destiné à confirmer l'utilisation de l'anglais dans le contexte de l'informatique ainsi que dans la pratique professionnelle.
				</resume>
				<plan>Cours/TD/TP : 10h/10h/10h</plan>
				<lieu>Luminy</lieu>
			</unite>
			
			<unite role="obligatoire" id="ENSINBU2">
				<nom>Communication</nom>
				<nbCredits>3</nbCredits>
				<resume>
				chapitre 1  : Théories de la communication :

				1.1 La théorie mathématique de l’information (Shannon, Weaver), la cybernétique (Wiener)
				1.2 La théorie de Palo Alto ( Bateson, Watzlawick) et la théorie de la communication par les processus (Mucchielli)
				chapitre 2 : Rôle de l’interculturalité dans le travail en équipe :

				2.1 L’enquête interculturelle de Hofstede pour IBM
				2.2 La gestuelle et le paralangage et la proxémie dans le monde (Hall)
				chapitre 3 : Notions de management et de travail collaboratif

				3.1 Le travail collaboratif vs le travail coopératif
				3.2 La notion de groupes
				3.3 Les compétences managériales
				Pré-requis :

				Particulièrement utile pour un choix d’options, les échanges internationaux et la formation continue.
				</resume>
				<plan>Cours/TD : 15h/8h</plan>
				<lieu>Luminy</lieu>
			</unite>
			 
			<unite role="obligatoire" id="ENSINBU4">
				<nom>XML</nom>
				<ref-intervenant ref="massat"/>
				<nbCredits>3</nbCredits>
				<resume>
					XML, DTD, XSD
					XPath, XSLT, XQuery
				</resume>
				<plan>Cours/TD/TP : 10h/10h/10h</plan>
				<lieu>Luminy</lieu>
			</unite> 
			
			<unite role="obligatoire" id="ENSINBU5">
				<nom>Algorithme et recherche opérationelle</nom>
				<ref-intervenant ref="chepoi"/>
				<nbCredits>3</nbCredits>
				<resume>
					Programmation linéaire.
					Notions et algorithmes de flots.
					Applications (couplage, affectation, transport, ...)
					Programmation dynamique (sac à dos, ordonnancement, ...)
					Algorithmes à performance garantie
				</resume>
				<plan>Cours/TD/TP : 10h/10h/10h</plan>
				<lieu>Luminy</lieu>
			</unite>
			 
			<unite role="obligatoire" id="ENSINBU15">
				<nom>Programmation parallèle</nom>
				<ref-intervenant ref="morin"/>
				<nbCredits>3</nbCredits>
				<resume>
					nous sommes désolé, mais nous n'avons pas encore de resume.
				</resume>
				<plan>Cours/TD/TP : 10h/10h/10h</plan>
				<lieu>Luminy</lieu>
			</unite>
			 
			<unite role="option" id="ENSINBU6">
				<nom>Projet</nom>
				<nbCredits>6</nbCredits>
				<resume>
					Le but du projet est de mettre en oeuvre, de l'analyse à la programmation, les notions présentées en cours. C'est l'occasion, pour les étudiants, d'utiliser sur un cas pratique, les éléments exposées dans les UE. Travail effectué sous la direction pédagogique d'un enseignant, et donnant lieu à la rédaction d'un mémoire et d'une soutenance orale.
				</resume>
				<plan>Cours/TD/TP : 10h/10h/10h</plan>
				<lieu>Luminy</lieu>
			</unite>
			 
			<unite role="option" id="ENSINBU7">
				<nom>Stage de deux moins</nom>
				<nbCredits>6</nbCredits>
				<resume>
					Le but du projet est de mettre en oeuvre, de l'analyse à la programmation, les notions présentées en cours. C'est l'occasion, pour les étudiants, d'utiliser sur un cas pratique, les éléments exposées dans les UE. Travail effectué sous la direction pédagogique d'un enseignant, et donnant lieu à la rédaction d'un mémoire et d'une soutenance orale.
